categories:
- Data Managers
description: Tiberius data manager
homepage_url: 'https://github.com/Gaius-Augustus/Tiberius'
long_description: 'Download reference model for Tiberius'
name: data_manager_tiberius
owner: mike
type: unrestricted
