categories:
- Data Managers
description: Tiberius data manager
homepage_url: 'https://github.com/Gaius-Augustus/Tiberius'
long_description: 'Download reference model for Tiberius'
name: data_manager_tiberius
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/data_managers/data_manager_tiberius
type: unrestricted
